My Project: class_traintest.OneHotEncoding Class Reference
class_traintest.OneHotEncoding Class Reference
Public Member Functions
def __init__ (self, custom_rcParams, df_nomiss_cat, type_)
def onehot_encoding (self)
def create_xy_frames (self, df_float, target)
def sample_imbalance (self, df_float, target)
def split_xtrain_ytrain (self, df_float, target)
Public Member Functions inherited from class_base.Base
def __init__ (self, custom_rcParams)
def plotting (self, title_, xlabel_, ylabel_)
def plot_legend (self, dict key_color)
Public Attributes
df_nomiss_cat
type
df_nomiss_cat_
axs
Public Attributes inherited from class_base.Base
custom_rcParams
Detailed Description
Definition at line 32 of file class_traintest.py.
Constructor & Destructor Documentation
__init__()
def class_traintest.OneHotEncoding.__init__ (self, custom_rcParams, df_nomiss_cat, type_)
Definition at line 34 of file class_traintest.py.
     def __init__(self, custom_rcParams, df_nomiss_cat, type_):
         super().__init__(custom_rcParams)
         self.df_nomiss_cat = df_nomiss_cat
         self.type = type_
Member Function Documentation
create_xy_frames()
def class_traintest.OneHotEncoding.create_xy_frames (self, df_float, target)
Definition at line 72 of file class_traintest.py.
     def create_xy_frames(self, df_float, target):
         if self.type == "machine":
             df_cat = self.onehot_encoding()
             df_total_partition = pd.concat([df_float, df_cat], axis = 1)
             x = df_total_partition.drop(labels=[target.name], axis=1)
             y = df_total_partition[target.name]
             return x, y
         elif self.type == "statistics":
             df_cat = self.onehot_encoding()
             df_total_partition = pd.concat([df_float, df_cat], axis = 1)
             x = df_total_partition.drop(labels=[target.name], axis=1)
             y = df_total_partition[target.name]
             return x, y
References class_traintest.OneHotEncoding.onehot_encoding(), and class_traintest.OneHotEncoding.type.
onehot_encoding()
def class_traintest.OneHotEncoding.onehot_encoding (self)
One Hot Encoding Function
Definition at line 40 of file class_traintest.py.
     def onehot_encoding(self):
         '''One Hot Encoding Function'''
         if self.type == "machine":
             encoded_dataframes = []
             for col in self.df_nomiss_cat.columns:
                 y = pd.get_dummies(self.df_nomiss_cat[col]).astype(int)
                 encoded_dataframes.append(y)
             df_cat_onehotenc = pd.concat(encoded_dataframes, axis = 1)
             return df_cat_onehotenc
         elif self.type == "statistics":
             encoded_dataframes = []
             for col in self.df_nomiss_cat.columns:
                 y = pd.get_dummies(self.df_nomiss_cat[col]).astype(int)
                 n = len(pd.unique(self.df_nomiss_cat[col]))
                 self.df_nomiss_cat_ = y.drop(y.columns[n-1], axis=1)
                 encoded_dataframes.append(self.df_nomiss_cat_)
             df_cat_onehotenc = pd.concat(encoded_dataframes, axis = 1)
             return df_cat_onehotenc
References class_traintest.OneHotEncoding.df_nomiss_cat, and class_traintest.OneHotEncoding.type.
sample_imbalance()
def class_traintest.OneHotEncoding.sample_imbalance (self, df_float, target)
Definition at line 92 of file class_traintest.py.
     def sample_imbalance(self, df_float, target):
         x, y = self.create_xy_frames(df_float, target)
         self.fig, self.axs = plt.subplots(1,1)
         self.axs.hist(y, weights = np.ones(len(y))/len(y))
         super().plotting("Normality Test", "x", "y")
         self.axs.hist(y, weights = np.ones(len(y))/len(y))
         self.axs.yaxis.set_major_formatter(PercentFormatter(1))
         return self.fig
References class_traintest.OneHotEncoding.create_xy_frames().
split_xtrain_ytrain()
def class_traintest.OneHotEncoding.split_xtrain_ytrain (self, df_float, target)
Definition at line 103 of file class_traintest.py.
     def split_xtrain_ytrain(self, df_float, target):
         x, y = self.create_xy_frames(df_float, target)
         x_train_pd, x_test_pd, y_train_pd, y_test_pd = train_test_split(x, y, test_size=0.3, random_state=42)
         x_train_pd = x_train_pd.drop(labels=["_freq_"], axis=1) # temp, for mach it has to be dropped
         x_test_pd = x_test_pd.drop(labels=["_freq_"], axis=1) # temp
         return x_train_pd, x_test_pd, y_train_pd, y_test_pd
References class_traintest.OneHotEncoding.create_xy_frames().
Member Data Documentation
axs
class_traintest.OneHotEncoding.axs
Definition at line 95 of file class_traintest.py.
df_nomiss_cat
class_traintest.OneHotEncoding.df_nomiss_cat
Definition at line 37 of file class_traintest.py.
df_nomiss_cat_
class_traintest.OneHotEncoding.df_nomiss_cat_
Definition at line 65 of file class_traintest.py.
type
class_traintest.OneHotEncoding.type
Definition at line 38 of file class_traintest.py.
The documentation for this class was generated from the following file:
class_traintest.py