# Generated by Django 4.2.4 on 2023-09-12 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("decision", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecProbability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("probability", models.FloatField(null=True)),
                ("default", models.CharField(max_length=20, null=True)),
                (
                    "dec_features_key",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="probability",
                        to="decision.decfeatures",
                    ),
                ),
            ],
        ),
    ]
